#!/usr/bin/env bash
# Usage: erlenv release-file-read <file>
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

RELEASE_FILE="$1"

if [ -e "$RELEASE_FILE" ]; then
  # Read the first non-whitespace word from the specified release file.
  # Be careful not to load it whole in case there's something crazy in it.
  release=""
  while read -a words; do
    word="${words[0]}"
    if [ -z "$release" ] && [ -n "$word" ]; then
      release="$word"
    fi
  done < <( cat "$RELEASE_FILE" && echo )

  if [ -n "$release" ]; then
    echo "$release"
    exit
  fi
fi

exit 1
