#!/usr/bin/env bash
# Summary: List existing erlenv shims
# Usage: erlenv shims [--short]

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# Provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${ERLENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
