#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# Provide erlenv completions
if [ "$1" = "--complete" ]; then
  exec erlenv-rehash --complete
fi

# When erlenv shell integration is enabled, delegate to erlenv-rehash,
# then tell the shell to empty its command lookup cache.
erlenv-rehash
echo "hash -r 2>/dev/null || true"
