#!/usr/bin/env bash
# Summary: Display the version of erlenv
#
# Displays the version number of this erlenv version, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <release>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.
#
# Note that we mirror the version of rbenv and do not increment
# unilaterally. Changes that would also change the behavior of
# rbenv are avoided unless absolutely necessary

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

version="0.4.0"

if cd "$ERLENV_ROOT" 2>/dev/null; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "erlenv ${git_revision:-$version}"
