#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: erlenv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "erlenv-$COMMAND" || command -v "erlenv-sh-$COMMAND")"
if grep -i "^# provide erlenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
