#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.erlenv-version" ]; then
      echo "${root}/.erlenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$ERLENV_DIR"
[ "$ERLENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_release_file="${ERLENV_ROOT}/release"

if [ -e "$global_release_file" ]; then
  echo "$global_release_file"
elif [ -e "${ERLENV_ROOT}/global" ]; then
  echo "${ERLENV_ROOT}/global"
elif [ -e "${ERLENV_ROOT}/default" ]; then
  echo "${ERLENV_ROOT}/default"
else
  echo "$global_release_file"
fi
