#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec erlenv-releases --bare
fi

release="$1"

if [ -z "$release" ]; then
  if [ -z "$ERLENV_RELEASE" ]; then
    echo "erlenv: no shell-specific release configured" >&2
    exit 1
  else
    echo "echo \"\$ERLENV_RELEASE\""
    exit
  fi
fi

if [ "$release" = "--unset" ]; then
  echo "unset ERLENV_VERSION"
  exit
fi

# Make sure the specified version is installed.
if erlenv-prefix "$release" >/dev/null; then
  echo "export ERLENV_RELEASE=\"${release}\""
else
  echo "return 1"
  exit 1
fi
