#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

ERLENV_RELEASE_FILE="$1"
ERLENV_RELEASE="$2"

if [ -z "$ERLENV_RELEASE" ] || [ -z "$ERLENV_RELEASE_FILE" ]; then
  echo "usage: erlenv release-file-write FILENAME RELEASE" >&2
  exit 1
fi

# make sure the specified release is installed
erlenv-prefix "$ERLENV_RELEASE" >/dev/null

# write the release out to disk
echo "$ERLENV_RELEASE" > "$ERLENV_RELEASE_FILE"
