#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

ERLENV_RELEASE_NAME="$(erlenv-release-name)"

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  print_release="$ERLENV_RELEASE_NAME"
else
  hit_prefix="* "
  miss_prefix="  "
  print_release="$(erlenv-release)"
fi

for path in "${ERLENV_ROOT}/releases/"*; do
  if [ -d "$path" ]; then
    release="${path##*/}"

    if [ "$release" == "$ERLENV_RELEASE_NAME" ]; then
      echo "${hit_prefix}${print_release}"
    else
      echo "${miss_prefix}${release}"
    fi
  fi
done
