#!/usr/bin/env bash
# Summary: Explain how the current erlang release is set
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

if [ -n "$ERLENV_RELEASE" ]; then
  echo "ERLENV_RELEASE environment variable"
else
  erlenv-release-file
fi
