#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec erlenv-releases --bare
fi

ERLENV_RELEASE="$1"
ERLENV_RELEASE_FILE="${ERLENV_ROOT}/release"

if [ -n "$ERLENV_RELEASE" ]; then
  erlenv-release-file-write "$ERLENV_RELEASE_FILE" "$ERLENV_RELEASE"
else
  erlenv-release-file-read "$ERLENV_RELEASE_FILE" ||
  erlenv-release-file-read "${ERLENV_ROOT}/global" ||
  erlenv-release-file-read "${ERLENV_ROOT}/default" ||
  echo system
fi
