#!/usr/bin/env bash
# Summary: List hook scripts for a given rbenv command
# Usage: rbenv hooks <command>

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

ERLENV_COMMAND="$1"
if [ -z "$ERLENV_COMMAND" ]; then
  erlenv-help --usage hooks >&2
  exit 1
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

realpath() {
  local cwd="$(pwd)"
  local base="$(basename $1)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/$base"
  cd "$cwd"
}

shopt -s nullglob
for path in ${ERLENV_HOOK_PATH//:/$'\n'}; do
  for script in $path/"$ERLENV_COMMAND"/*.bash; do
    echo $(realpath $script)
  done
done
shopt -u nullglob
