#!/usr/bin/env bash
# Summary: Display the version of erlenv
#
# Displays the version number of this erlenv release

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

version="0.4.0"

echo "erlenv ${version}"
