#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# provide rbenv completions
if [ "$1" = "--complete" ]; then
  exec erlenv shims --short
fi

export ERLENV_VERSION="$(rbenv-version-name)"
ERLENV_COMMAND="$1"

if [ -z "$ERLENV_COMMAND" ]; then
  echo "usage: erlenv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

ERLENV_COMMAND_PATH="$(erlenv-which "$ERLENV_COMMAND")"
ERLENV_BIN_PATH="${ERLENV_COMMAND_PATH%/*}"

for script in $(erlenv-hooks exec); do
  source "$script"
done

shift 1
if [ "$ERLENV_VERSION" != "system" ]; then
  export PATH="${ERLENV_BIN_PATH}:${PATH}"
fi
exec -a "$ERLENV_COMMAND" "$ERLENV_COMMAND_PATH" "$@"