#!/usr/bin/env bash
set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec erlenv-releases --bare
fi

if [ -n "$1" ]; then
  export ERLENV_RELEASE="$1"
elif [ -z "$ERLENV_RELEASE" ]; then
  ERLENV_RELEASE="$(erlenv-release-name)"
fi

if [ "$ERLENV_VERSION" = "system" ]; then
  ERL_PATH="$(erlenv-which erl)"
  ERL_PATH="${ERL_PATH%/*}"
  echo "${ERL_PATH%/bin}"
  exit
fi

ERLENV_PREFIX_PATH="${ERLENV_ROOT}/releases/${ERLENV_RELEASE}"
if [ ! -d "$ERLENV_PREFIX_PATH" ]; then
  echo "erlenv: release \`${ERLENV_RELEASE}' not installed" >&2
  exit 1
fi

echo "$ERLENV_PREFIX_PATH"
