#!/usr/bin/env bash
# Summary: List existing rbenv shims
# Usage: rbenv shims [--short]

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

for command in "${ERLENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
