#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific erlang release
#
# Usage: erlenv shell <version>
#        erlenv shell --unset
#
# Sets a shell-specific erlang release by setting the `ERLENV_RELEASE'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <release> should be a string matching a erlang release known to erlenv.
# The special version string `system' will use your default system erlang.
# Run `erlenv releases' for a list of available erlang releases.

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# Provide erlenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec erlenv-versions --bare
fi

release="$1"
shell="$(basename "$SHELL")"

if [ -z "$release" ]; then
  if [ -z "$ERLENV_RELEASE" ]; then
    echo "erlenv: no shell-specific release configured" >&2
    exit 1
  else
    echo "echo \"\$ERLENV_RELEASE\""
    exit
  fi
fi

if [ "$release" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e ERLENV_RELEASE"
    ;;
  * )
    echo "unset ERLENV_RELEASE"
    ;;
  esac
  exit
fi

# Make sure the specified release is installed.
if erlenv-prefix "$release" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv ERLENV_RELEASE \"${release}\""
    ;;
  * )
    echo "export ERLENV_RELEASE=\"${release}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
