#!/usr/bin/env bash
#
# Summary: Display prefix for a erlang release
#
# Usage: erlenv prefix [<release>]
#
# Displays the directory where an erlang release is installed. If no
# release is given, `erlenv prefix' displays the location of the
# currently selected release.

set -e
[ -n "$ERLENV_DEBUG" ] && set -x

# Provide erlenv completions
if [ "$1" = "--complete" ]; then
echo system
  exec erlenv-releases --bare
fi

if [ -n "$1" ]; then
  export ERLENV_RELEASE="$1"
elif [ -z "$ERLENV_RELEASE" ]; then
  ERLENV_RELEASE="$(erlenv-release-name)"
fi

if [ "$ERLENV_RELEASE" = "system" ]; then
  if output=$(erlenv-system); then
    ERLENV_PREFIX_PATH=${output%/bin}
  fi
else
  ERLENV_PREFIX_PATH="${ERLENV_ROOT}/releases/${ERLENV_RELEASE}"
fi

if [ ! -d "$ERLENV_PREFIX_PATH" ]; then
  echo "erlenv: release \`${ERLENV_RELEASE}' not installed" >&2
  exit 1
fi

echo "$ERLENV_PREFIX_PATH"